CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "email" varchar(254) UNIQUE NOT NULL,
  "username" varchar(64) NOT NULL,
  "password_hash" varchar(72) NOT NULL,
  "encrypted_2fa_secret" varchar(128) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(32) UNIQUE NOT NULL
);

CREATE TABLE "user_roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "role_id" int NOT NULL,
  "user_id" int NOT NULL
);

CREATE TABLE "teams" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(32) NOT NULL,
  "owner_user_id" int NOT NULL
);

CREATE TABLE "team_members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "team_id" int NOT NULL,
  "user_id" int NOT NULL
);

CREATE TABLE "todos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar(64) NOT NULL,
  "description" varchar(256) NOT NULL,
  "created_at" timestamp NOT NULL,
  "due_date" timestamp NOT NULL,
  "team_id" int NOT NULL,
  "completed_at" timestamp,
  "assigned_user_id" int
);

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");
ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "teams" ADD FOREIGN KEY ("owner_user_id") REFERENCES "users" ("id");
ALTER TABLE "team_members" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");
ALTER TABLE "team_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "todos" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");
ALTER TABLE "todos" ADD FOREIGN KEY ("assigned_user_id") REFERENCES "users" ("id");
