name: CDK-MIGRATIONS-CICD

on:
  push:
    branches: [cicd-setup]
    paths: ["migrations/**", "cdk-todo-app/**"]
  pull_request:
    branches: [cicd-setup]
    paths: ["migrations/**", "cdk-todo-app/**"]
env:
  AWS_REGION: af-south-1

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: cdk-todo-app

jobs:
  AWS-CDK-MIGRATIONS:
    runs-on: [ubuntu-latest]
    steps:
      - name: Configure AWS Credentials Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::387198229710:role/github-actions #NEVER CHANGE THIS
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{env.AWS_REGION}}

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 🧰 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependecies
        run: npm i

      - name: Bootstrap cdk
        run: npx cdk bootstrap

      - name: Deploy cdk changes
        run: npx cdk deploy --require-approval never

      - name: Get DB Connection Information
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            CdkTodoAppStacktodoapppostg
          parse-json-secrets: true

      - name: Run DB Migrations
        run: |
          docker run --rm --volume ${{ github.workspace }}/migrations:/flyway/sql:ro redgate/flyway -url="jdbc:postgresql://${{env.CDKTODOAPPSTACKTODOAPPPOSTG_HOST}}:5432/${{env.CDKTODOAPPSTACKTODOAPPPOSTG_DBNAME}}" -user="${{ env.CDKTODOAPPSTACKTODOAPPPOSTG_USERNAME }}" -password="${{ env.CDKTODOAPPSTACKTODOAPPPOSTG_PASSWORD }}" repair
          docker run --rm --volume ${{ github.workspace }}/migrations:/flyway/sql:ro redgate/flyway -url="jdbc:postgresql://${{env.CDKTODOAPPSTACKTODOAPPPOSTG_HOST}}:5432/${{env.CDKTODOAPPSTACKTODOAPPPOSTG_DBNAME}}" -user="${{ env.CDKTODOAPPSTACKTODOAPPPOSTG_USERNAME }}" -password="${{ env.CDKTODOAPPSTACKTODOAPPPOSTG_PASSWORD }}" migrate
