name: CDK-CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: cdk-todo-app

jobs:
  AWS-CDK-MIGRATIONS:
    runs-on: [ubuntu-latest]
    steps:
      - name: Configure AWS Credentials Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::387198229710:role/github-actions #NEVER CHANGE THIS
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{env.AWS_REGION}}

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 🧰 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependecies
        run: |
          npm i

      - name: Bootstrap cdk
        run: npx cdk bootstrap

      - name: Deploy cdk changes
        run: npx cdk deploy --require-approval never
