name: CICD

on:
  push:
    branches: [cicd-setup]
  pull_request:
    branches: [cicd-setup]
env:
  AWS_REGION: af-south-1

permissions:
  id-token: write
  contents: read

jobs:
  configure_aws:
    runs-on: [ubuntu-latest]
    steps:
      - name: Configure AWS Credentials Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::387198229710:role/github-actions
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{env.AWS_REGION}}
      - name: hello from aws
        run: |
          aws sts get-caller-identity
          export
